// web/src/views/LoginView.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { authApi } from '@/api/auth'

const router = useRouter()
const username = ref('')
const password = ref('')
const isLoading = ref(false)
const errorMessage = ref('')

const handleLogin = async () => {
  if (!username.value || !password.value) {
    errorMessage.value = 'Please fill in all fields.'
    return
  }

  isLoading.value = true
  errorMessage.value = ''

  try {
    const response = await authApi.login({
      username: username.value,
      password: password.value,
    })

    // Store token
    localStorage.setItem('access_token', response.access_token)
    localStorage.setItem('user', JSON.stringify(response.user))

    // Redirect to home
    router.push({ name: 'home' })
  } catch (error: any) {
    errorMessage.value = error.message || 'Login failed. Please check your credentials.'
  } finally {
    isLoading.value = false
  }
}
</script>

<template>
  <div class="login-page">
    <div class="login-card">
      <div class="header">
        <div class="logo-box">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/></svg>
        </div>
        <h2 class="title">Welcome back</h2>
        <p class="subtitle">Log in to your account to continue</p>
      </div>

      <form class="login-form" @submit.prevent="handleLogin">
        <div class="form-groups">
          <div class="form-group">
            <label for="username" class="label">Username</label>
            <input
              id="username"
              name="username"
              type="text"
              autocomplete="username"
              required
              v-model="username"
              class="input-field"
              placeholder="Your username"
            />
          </div>
          <div class="form-group">
            <label for="password" class="label">Password</label>
            <input
              id="password"
              name="password"
              type="password"
              autocomplete="current-password"
              required
              v-model="password"
              class="input-field"
              placeholder="••••••••"
            />
          </div>
        </div>

        <div v-if="errorMessage" class="error-message">
          {{ errorMessage }}
        </div>

        <div class="submit-container">
          <button
            type="submit"
            :disabled="isLoading"
            class="submit-button"
          >
            <span v-if="isLoading" class="loader-container">
              <svg class="animate-spin" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
            </span>
            {{ isLoading ? 'Logging in...' : 'Log in' }}
          </button>
        </div>

        <div class="footer">
          <p class="footer-text">
            Don't have an account?
            <router-link :to="{ name: 'register' }" class="signup-link">
              Sign up
            </router-link>
          </p>
        </div>
      </form>
    </div>
  </div>
</template>

<style scoped>
@reference "tailwindcss";

.login-page {
  @apply min-h-screen flex items-center justify-center bg-[var(--claude-bg)] px-4 py-12;
}

.login-card {
  @apply w-full max-w-md space-y-8;
}

.header {
  @apply text-center;
}

.logo-box {
  @apply mx-auto h-12 w-12 flex items-center justify-center rounded-xl bg-[var(--claude-primary)] text-white shadow-sm mb-6;
}

.title {
  @apply text-4xl text-[var(--claude-text)] tracking-tight font-serif;
}

.subtitle {
  @apply mt-3 text-[var(--claude-muted)] font-medium;
}

.login-form {
  @apply mt-8 space-y-6;
}

.form-groups {
  @apply space-y-4;
}

.form-group {
  @apply flex flex-col;
}

.label {
  @apply block text-sm font-medium text-[var(--claude-text)] mb-1;
}

.input-field {
  @apply appearance-none block w-full px-4 py-3 border border-[var(--claude-border)] rounded-xl placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-[var(--claude-focus)] focus:border-transparent transition-all duration-200 bg-[var(--claude-input-bg)] text-[var(--claude-text)];
}

.error-message {
  @apply text-red-500 text-sm bg-red-50 p-3 rounded-lg border border-red-100;
  animation: fadeIn 0.2s ease-out;
}

@keyframes fadeIn {
  from { opacity: 0; transform: translateY(-4px); }
  to { opacity: 1; transform: translateY(0); }
}

.submit-container {
  @apply w-full;
}

.submit-button {
  @apply relative w-full flex justify-center py-3 px-4 border border-transparent text-sm font-semibold rounded-xl text-white bg-[var(--claude-primary)] hover:bg-[var(--claude-primary-hover)] focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-[var(--claude-focus)] transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed shadow-md hover:shadow-lg active:scale-[0.98];
}

.loader-container {
  @apply absolute left-0 inset-y-0 flex items-center pl-3;
}

.loader-container svg {
  @apply h-5 w-5 text-white;
}

.footer {
  @apply text-center;
}

.footer-text {
  @apply text-sm text-[var(--claude-muted)];
}

.signup-link {
  @apply font-semibold text-[var(--claude-primary)] hover:underline decoration-2 underline-offset-4;
}

.font-serif {
  font-family: Charter, 'Iowan Old Style', 'Palatino Linotype', 'URW Palladio L', P052, Palatino, 'Book Antiqua', Georgia, serif;
}
</style>

// web/src/pages/LoginView.tsx
import { FormEvent, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Layers3, Loader2 } from "lucide-react";
import { motion } from "motion/react";
import { useAuthStore } from "@/store/auth";

import { authApi } from "@/api/auth";

export default function LoginView() {
  const navigate = useNavigate();
  const setAuth = useAuthStore((state) => state.setAuth);
  
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");

  const handleLogin = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (!username.trim() || !password) {
      setErrorMessage("Please fill in all fields.");
      return;
    }

    if (username.trim().length < 3) {
      setErrorMessage("Username must be at least 3 characters.");
      return;
    }

    if (password.length < 6) {
      setErrorMessage("Password must be at least 6 characters.");
      return;
    }

    setIsLoading(true);
    setErrorMessage("");

    try {
      const response = await authApi.login({
        username: username.trim(),
        password,
      });

      setAuth(response.access_token, response.user);
      navigate("/", { replace: true });
    } catch (error) {
      setErrorMessage(
        error instanceof Error
          ? error.message
          : "Login failed. Please check your credentials.",
      );
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <main className="auth-page grid min-h-screen place-items-center p-6 bg-gradient-to-b from-[#fbfbfd] to-[#f5f5f7]">
      <motion.section 
        className="apple-panel w-full max-w-[460px] p-10 py-12" 
        aria-labelledby="login-title"
        initial={{ opacity: 0, y: 40, scale: 0.98 }}
        animate={{ opacity: 1, y: 0, scale: 1 }}
        transition={{ type: "spring", stiffness: 100, damping: 20, mass: 1 }}
      >
        <div className="text-center mb-10">
          <motion.div 
            initial={{ scale: 0.5, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            transition={{ delay: 0.2 }}
            className="inline-flex h-16 w-16 items-center justify-center bg-black text-white rounded-[18px] mb-5 shadow-[0_10px_30px_rgba(0,0,0,0.15)]"
          >
            <Layers3 size={32} strokeWidth={2.2} />
          </motion.div>
          <p className="text-[12px] font-bold text-[#86868b] uppercase tracking-[0.1em] mb-2">
            multi-agent-s2c
          </p>
          <h1 id="login-title" className="apple-title">
            Welcome Back
          </h1>
        </div>

        <form className="flex flex-col gap-5" onSubmit={handleLogin}>
          <div>
            <label className="apple-label" htmlFor="username">Username</label>
            <input
              id="username"
              autoComplete="username"
              className="apple-input"
              onChange={(event) => setUsername(event.target.value)}
              placeholder="Your username"
              type="text"
              value={username}
            />
          </div>

          <div>
            <label className="apple-label" htmlFor="password">Password</label>
            <input
              id="password"
              autoComplete="current-password"
              className="apple-input"
              onChange={(event) => setPassword(event.target.value)}
              placeholder="Password"
              type="password"
              value={password}
            />
          </div>

          {errorMessage ? (
            <motion.div 
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              className="auth-message auth-message-error"
            >
              {errorMessage}
            </motion.div>
          ) : null}

          <button className="apple-btn mt-3" disabled={isLoading} type="submit">
            {isLoading ? <Loader2 className="spin" size={20} /> : "Sign In"}
          </button>
        </form>

        <p className="apple-footer">
          New here?{" "}
          <Link className="apple-link" to="/register">
            Create an account
          </Link>
        </p>
      </motion.section>
    </main>
  );
}
