// web/src/views/RegisterView.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { authApi } from '@/api/auth'

const router = useRouter()
const username = ref('')
const password = ref('')
const isLoading = ref(false)
const errorMessage = ref('')
const successMessage = ref('')

const handleRegister = async () => {
  if (!username.value || !password.value) {
    errorMessage.value = 'Please fill in all fields.'
    return
  }

  isLoading.value = true
  errorMessage.value = ''
  successMessage.value = ''

  try {
    await authApi.register({
      username: username.value,
      password: password.value,
    })

    successMessage.value = 'Registration successful! Redirecting to login...'
    setTimeout(() => {
      router.push({ name: 'login' })
    }, 2000)
  } catch (error: any) {
    errorMessage.value = error.message || 'Registration failed. Please try again.'
  } finally {
    isLoading.value = false
  }
}
</script>

<template>
  <div class="register-page">
    <div class="register-card">
      <div class="header">
        <div class="logo-box">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/></svg>
        </div>
        <h2 class="title">Create an account</h2>
        <p class="subtitle">Join us and start generating</p>
      </div>

      <form class="register-form" @submit.prevent="handleRegister">
        <div class="form-groups">
          <div class="form-group">
            <label for="username" class="label">Username</label>
            <input
              id="username"
              name="username"
              type="text"
              required
              v-model="username"
              class="input-field"
              placeholder="johndoe"
            />
          </div>
          <div class="form-group">
            <label for="password" class="label">Password</label>
            <input
              id="password"
              name="password"
              type="password"
              autocomplete="new-password"
              required
              v-model="password"
              class="input-field"
              placeholder="••••••••"
            />
          </div>
        </div>

        <div v-if="errorMessage" class="error-message">
          {{ errorMessage }}
        </div>

        <div v-if="successMessage" class="success-message">
          {{ successMessage }}
        </div>

        <div class="submit-container">
          <button
            type="submit"
            :disabled="isLoading"
            class="submit-button"
          >
            <span v-if="isLoading" class="loader-container">
              <svg class="animate-spin" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
            </span>
            {{ isLoading ? 'Creating account...' : 'Create account' }}
          </button>
        </div>

        <div class="footer">
          <p class="footer-text">
            Already have an account?
            <router-link :to="{ name: 'login' }" class="login-link">
              Log in
            </router-link>
          </p>
        </div>
      </form>
    </div>
  </div>
</template>

<style scoped>
@reference "tailwindcss";

.register-page {
  @apply min-h-screen flex items-center justify-center bg-[var(--claude-bg)] px-4 py-12;
}

.register-card {
  @apply w-full max-w-md space-y-8;
}

.header {
  @apply text-center;
}

.logo-box {
  @apply mx-auto h-12 w-12 flex items-center justify-center rounded-xl bg-[var(--claude-primary)] text-white shadow-sm mb-6;
}

.title {
  @apply text-4xl text-[var(--claude-text)] tracking-tight font-serif;
}

.subtitle {
  @apply mt-3 text-[var(--claude-muted)] font-medium;
}

.register-form {
  @apply mt-8 space-y-6;
}

.form-groups {
  @apply space-y-4;
}

.form-group {
  @apply flex flex-col;
}

.label {
  @apply block text-sm font-medium text-[var(--claude-text)] mb-1;
}

.input-field {
  @apply appearance-none block w-full px-4 py-3 border border-[var(--claude-border)] rounded-xl placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-[var(--claude-focus)] focus:border-transparent transition-all duration-200 bg-[var(--claude-input-bg)] text-[var(--claude-text)];
}

.error-message {
  @apply text-red-500 text-sm bg-red-50 p-3 rounded-lg border border-red-100;
  animation: fadeIn 0.2s ease-out;
}

.success-message {
  @apply text-green-600 text-sm bg-green-50 p-3 rounded-lg border border-green-100;
  animation: fadeIn 0.2s ease-out;
}

@keyframes fadeIn {
  from { opacity: 0; transform: translateY(-4px); }
  to { opacity: 1; transform: translateY(0); }
}

.submit-container {
  @apply w-full;
}

.submit-button {
  @apply relative w-full flex justify-center py-3 px-4 border border-transparent text-sm font-semibold rounded-xl text-white bg-[var(--claude-primary)] hover:bg-[var(--claude-primary-hover)] focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-[var(--claude-focus)] transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed shadow-md hover:shadow-lg active:scale-[0.98];
}

.loader-container {
  @apply absolute left-0 inset-y-0 flex items-center pl-3;
}

.loader-container svg {
  @apply h-5 w-5 text-white;
}

.footer {
  @apply text-center;
}

.footer-text {
  @apply text-sm text-[var(--claude-muted)];
}

.login-link {
  @apply font-semibold text-[var(--claude-primary)] hover:underline decoration-2 underline-offset-4;
}

.font-serif {
  font-family: Charter, 'Iowan Old Style', 'Palatino Linotype', 'URW Palladio L', P052, Palatino, 'Book Antiqua', Georgia, serif;
}
</style>

// web/src/pages/RegisterView.tsx
import { Alert, Button, Form, Input } from "antd";
import { Layers3 } from "lucide-react";
import { motion } from "motion/react";
import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";

import { authApi } from "@/api/auth";

type RegisterFormValues = {
  password: string;
  username: string;
};

export default function RegisterView() {
  const navigate = useNavigate();
  const [errorMessage, setErrorMessage] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [successMessage, setSuccessMessage] = useState("");

  const handleRegister = async (values: RegisterFormValues) => {
    setErrorMessage("");
    setSuccessMessage("");
    setIsLoading(true);

    try {
      await authApi.register({
        username: values.username.trim(),
        password: values.password,
      });

      setSuccessMessage("Account created. Redirecting to login...");
      window.setTimeout(() => {
        navigate("/login", { replace: true });
      }, 1500);
    } catch (error) {
      setErrorMessage(
        error instanceof Error
          ? error.message
          : "Registration failed. Please try again.",
      );
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <main className="grid min-h-screen place-items-center bg-main-background p-5">
      <motion.section
        aria-labelledby="register-title"
        className="w-full max-w-[400px] rounded-[18px] border border-border bg-card-background px-7 py-8 shadow-[0_16px_38px_rgba(44,44,44,0.08)]"
        initial={{ opacity: 0, y: 40, scale: 0.98 }}
        animate={{ opacity: 1, y: 0, scale: 1 }}
        transition={{ type: "spring", stiffness: 100, damping: 20, mass: 1 }}
      >
        <div className="mb-7 text-center">
          <motion.div
            initial={{ scale: 0.5, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            transition={{ delay: 0.2 }}
            className="mb-4 inline-flex h-11 w-11 items-center justify-center rounded-[12px] bg-accent text-primary-button-text shadow-[0_8px_20px_rgba(44,44,44,0.1)]"
          >
            <Layers3 size={23} strokeWidth={2.1} />
          </motion.div>
          <p className="mb-2 text-[11px] font-medium uppercase tracking-[0.1em] text-on-surface-variant">
            multi-agent-s2c
          </p>
          <h1
            id="register-title"
            className="m-0 text-[24px] font-medium leading-tight text-on-surface"
          >
            Create Account
          </h1>
        </div>

        <Form
          layout="vertical"
          onFinish={handleRegister}
          requiredMark={false}
        >
          <Form.Item
            label="Username"
            name="username"
            rules={[
              { required: true, message: "Please enter your username." },
              { min: 3, message: "Username must be at least 3 characters." },
            ]}
          >
            <Input autoComplete="username" placeholder="Your username" />
          </Form.Item>

          <Form.Item
            label="Password"
            name="password"
            rules={[
              { required: true, message: "Please enter your password." },
              { min: 6, message: "Password must be at least 6 characters." },
            ]}
          >
            <Input.Password
              autoComplete="new-password"
              placeholder="At least 6 characters"
            />
          </Form.Item>

          {errorMessage ? (
            <Alert className="mb-4" message={errorMessage} showIcon type="error" />
          ) : null}

          {successMessage ? (
            <Alert className="mb-4" message={successMessage} showIcon type="success" />
          ) : null}

          <Form.Item className="mb-0 mt-6">
            <Button block htmlType="submit" loading={isLoading} type="primary">
              Continue
            </Button>
          </Form.Item>
        </Form>

        <p className="mt-5 text-center text-[13px] font-medium text-on-surface-variant">
          Already have an account?{" "}
          <Link className="font-bold text-on-surface hover:text-accent-hover hover:underline" to="/login">
            Sign in
          </Link>
        </p>
      </motion.section>
    </main>
  );
}
